[package]
name = "ts-to-rust"
version = "0.1.0"
edition = "2024"


[dependencies]
solana-client = "1.10"
solana-sdk = "1.10"
dotenv = "0.15"
serde_json = "1.0.140"
bs58 = "0.5.1"
tokio = { version = "1", features = ["full"] }
