[package]
name = "rust-app"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
dotenv = "0.15.0"
serde_json = "1.0.140"
solana-client = "2.2.6"
solana-sdk = "2.2.2"
tokio = { version = "1", features = ["full"] }
